#!/usr/bin/env bash
# GLOBAL ORBIT MAIL — Nginx-only cutover (Next.js already on :3100)
# Does NOT rebuild the app. Only fixes routing so Roundcube is no longer public.
#
# Usage (VPS root):
#   curl -fsSL https://raw.githubusercontent.com/arnavganguly209-code/global-orbit-mail/main/deploy/vps/cutover-nginx-webmail.sh | bash
#
set -euo pipefail

WEBMAIL_HOST="${WEBMAIL_HOSTNAME:-webmail.globalorbitmail.cloud}"
APP_PORT="${ORBIT_WEBMAIL_PORT:-3100}"
UPSTREAM="127.0.0.1:${APP_PORT}"
TS="$(date +%Y%m%d%H%M%S)"
OUT_SITE="/etc/nginx/sites-available/webmail.globalorbitmail.cloud"
OUT_LINK="/etc/nginx/sites-enabled/webmail.globalorbitmail.cloud"

echo "=============================================="
echo " Nginx cutover → proxy ${WEBMAIL_HOST} → ${UPSTREAM}"
echo "=============================================="

need() { command -v "$1" >/dev/null 2>&1 || { echo "ERROR: missing $1" >&2; exit 1; }; }
need nginx
need curl
need awk
need sed
need grep

# Confirm Next is up
CODE="$(curl -s -o /dev/null -w '%{http_code}' "http://${UPSTREAM}/webmail/login" || true)"
if [[ "$CODE" != "200" && "$CODE" != "302" && "$CODE" != "307" && "$CODE" != "308" ]]; then
  echo "ERROR: Next.js not responding at http://${UPSTREAM}/webmail/login (HTTP ${CODE})" >&2
  echo "Start it first: pm2 start / show orbit-webmail" >&2
  exit 1
fi
echo "Next.js OK on ${UPSTREAM} (HTTP ${CODE})"

mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled /root/orbit-nginx-backups
BACKUP_DIR="/root/orbit-nginx-backups/${TS}"
mkdir -p "$BACKUP_DIR"

echo
echo "—— Active nginx units mentioning webmail / Roundcube ——"
find /etc/nginx -type f \( -name '*.conf' -o -path '*/sites-enabled/*' -o -path '*/sites-available/*' \) 2>/dev/null \
  | while read -r f; do
      if grep -Eiq "${WEBMAIL_HOST}|roundcube|/var/www/roundcube" "$f" 2>/dev/null; then
        echo "  $f"
        cp -a "$f" "$BACKUP_DIR/" 2>/dev/null || true
      fi
    done
echo "Backups → $BACKUP_DIR"
echo

# ── Detect existing valid cert/key for this host ──
detect_ssl_pair() {
  local host="$1"
  local cert="" key="" dump conf d base

  dump="$(nginx -T 2>/dev/null || true)"
  if [[ -n "$dump" ]]; then
    cert="$(printf '%s\n' "$dump" | awk -v h="$host" '
      BEGIN{inblk=0}
      /server_name/ && index($0,h){inblk=1}
      inblk && /ssl_certificate / && $0 !~ /ssl_certificate_key/ {
        gsub(/;/,""); print $2; exit
      }
      inblk && /^[[:space:]]*}/ {inblk=0}
    ')"
    key="$(printf '%s\n' "$dump" | awk -v h="$host" '
      BEGIN{inblk=0}
      /server_name/ && index($0,h){inblk=1}
      inblk && /ssl_certificate_key / {
        gsub(/;/,""); print $2; exit
      }
      inblk && /^[[:space:]]*}/ {inblk=0}
    ')"
    if [[ -n "$cert" && -f "$cert" && -n "$key" && -f "$key" ]]; then
      echo "$cert|$key"; return 0
    fi
  fi

  while IFS= read -r conf; do
    [[ -z "$conf" ]] && continue
    if grep -q "server_name.*${host}" "$conf" 2>/dev/null; then
      cert="$(grep -E '^\s*ssl_certificate\s+' "$conf" | grep -v certificate_key | head -1 | awk '{print $2}' | tr -d ';')"
      key="$(grep -E '^\s*ssl_certificate_key\s+' "$conf" | head -1 | awk '{print $2}' | tr -d ';')"
      if [[ -n "$cert" && -f "$cert" && -n "$key" && -f "$key" ]]; then
        echo "$cert|$key"; return 0
      fi
    fi
  done < <(find /etc/nginx -type f \( -name '*.conf' -o -path '*/sites-enabled/*' -o -path '*/sites-available/*' \) 2>/dev/null)

  if [[ -f "/etc/letsencrypt/live/${host}/fullchain.pem" && -f "/etc/letsencrypt/live/${host}/privkey.pem" ]]; then
    echo "/etc/letsencrypt/live/${host}/fullchain.pem|/etc/letsencrypt/live/${host}/privkey.pem"
    return 0
  fi

  for d in /etc/letsencrypt/live/*; do
    [[ -d "$d" ]] || continue
    base="$(basename "$d")"
    if [[ "$base" == *webmail* || "$base" == *globalorbitmail* || "$base" == "$host" ]]; then
      if [[ -f "$d/fullchain.pem" && -f "$d/privkey.pem" ]]; then
        echo "$d/fullchain.pem|$d/privkey.pem"; return 0
      fi
    fi
  done

  for d in /etc/letsencrypt/live/*; do
    [[ -d "$d" ]] || continue
    if [[ -f "$d/fullchain.pem" && -f "$d/privkey.pem" ]]; then
      echo "$d/fullchain.pem|$d/privkey.pem"; return 0
    fi
  done
  return 1
}

SSL_PAIR="$(detect_ssl_pair "$WEBMAIL_HOST" || true)"
if [[ -z "${SSL_PAIR:-}" ]]; then
  echo "ERROR: No valid SSL certificate/key found for ${WEBMAIL_HOST}" >&2
  exit 1
fi
SSL_CERT="${SSL_PAIR%%|*}"
SSL_KEY="${SSL_PAIR##*|}"
echo "TLS cert: $SSL_CERT"
echo "TLS key:  $SSL_KEY"

SSL_OPTIONS=""
SSL_DH=""
[[ -f /etc/letsencrypt/options-ssl-nginx.conf ]] && SSL_OPTIONS="include /etc/letsencrypt/options-ssl-nginx.conf;"
[[ -f /etc/letsencrypt/ssl-dhparams.pem ]] && SSL_DH="ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;"

# Write clean Next-only vhost
cat > "$OUT_SITE" <<EOF
# AUTO-GENERATED by cutover-nginx-webmail.sh (${TS})
# ${WEBMAIL_HOST} → Next.js ${UPSTREAM}  (Roundcube not served)

upstream orbit_webmail_upstream {
    server ${UPSTREAM};
    keepalive 32;
}

map \$arg__task \$orbit_is_roundcube_task {
    default 0;
    "~.+"   1;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${WEBMAIL_HOST};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${WEBMAIL_HOST};

    ssl_certificate     ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};
    ${SSL_OPTIONS}
    ${SSL_DH}

    client_max_body_size 50m;

    location ~* \\.php(/|\$) { return 301 /webmail/login; }
    location ~* ^/(skins|plugins|program|installer|bin|SQL|vendor|temp|logs)(/|\$) { return 301 /webmail/login; }
    location = /index.php { return 301 /webmail/login; }

    if (\$orbit_is_roundcube_task = 1) { return 301 /webmail/login; }

    location = / { return 302 /webmail/login; }

    location / {
        proxy_pass http://orbit_webmail_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
EOF

ln -sfn "$OUT_SITE" "$OUT_LINK"

# Disable EVERY other enabled unit that still claims this host or Roundcube UI
shopt -s nullglob
for f in /etc/nginx/sites-enabled/* /etc/nginx/conf.d/*; do
  [[ -e "$f" ]] || continue
  base="$(basename "$f")"
  [[ "$base" == "webmail.globalorbitmail.cloud" ]] && continue
  [[ "$base" == "orbit-webmail-next.conf" ]] && continue

  if grep -Eiq "server_name[[:space:]].*${WEBMAIL_HOST}|roundcube|/var/www/roundcube|root[[:space:]].*roundcube|try_files.*index\\.php" "$f" 2>/dev/null; then
    # Only disable if it also mentions this host OR is clearly Roundcube for mail UI
    if grep -Eiq "${WEBMAIL_HOST}|roundcube|/var/www/roundcube" "$f" 2>/dev/null; then
      echo "Disabling competing site: $f"
      rm -f "$f"
    fi
  fi
done
shopt -u nullglob

# Extra: rewrite any remaining enabled conf that still points this host at PHP/Roundcube
# (safety if a file wasn't matched above)
while IFS= read -r f; do
  [[ -z "$f" ]] && continue
  [[ "$(readlink -f "$f" 2>/dev/null || echo "$f")" == "$(readlink -f "$OUT_SITE")" ]] && continue
  if grep -q "server_name.*${WEBMAIL_HOST}" "$f" 2>/dev/null; then
    echo "Disabling leftover host claim: $f"
    rm -f "$f"
  fi
done < <(find /etc/nginx/sites-enabled /etc/nginx/conf.d -type f 2>/dev/null)

# nginx -t with auto-fix retries
for attempt in 1 2 3 4 5 6; do
  if nginx -t 2>/tmp/orbit-nginx-t.err; then
    echo "nginx -t OK (attempt ${attempt})"
    break
  fi
  echo "nginx -t FAILED (attempt ${attempt}):"
  cat /tmp/orbit-nginx-t.err >&2 || true

  if grep -qi "duplicate upstream" /tmp/orbit-nginx-t.err; then
    while IFS= read -r hit; do
      [[ -z "$hit" ]] && continue
      real="$(readlink -f "$hit" 2>/dev/null || echo "$hit")"
      [[ "$real" == "$(readlink -f "$OUT_SITE")" ]] && continue
      echo "Removing duplicate upstream file: $hit"
      rm -f "$hit"
    done < <(grep -Rl "orbit_webmail_upstream" /etc/nginx 2>/dev/null || true)
    continue
  fi

  if grep -qi "duplicate map" /tmp/orbit-nginx-t.err; then
    while IFS= read -r hit; do
      [[ -z "$hit" ]] && continue
      real="$(readlink -f "$hit" 2>/dev/null || echo "$hit")"
      [[ "$real" == "$(readlink -f "$OUT_SITE")" ]] && continue
      if grep -q "orbit_is_roundcube_task" "$hit" 2>/dev/null; then
        echo "Removing duplicate map file: $hit"
        rm -f "$hit"
      fi
    done < <(grep -Rl "orbit_is_roundcube_task" /etc/nginx 2>/dev/null || true)
    continue
  fi

  # Strip missing include/pem paths from our site
  while read -r p; do
    [[ -z "$p" ]] && continue
    if [[ ! -e "$p" ]] && grep -Fq "$p" "$OUT_SITE"; then
      echo "Stripping missing path: $p"
      sed -i "\|${p}|d" "$OUT_SITE"
    fi
  done < <(grep -Eo '/[A-Za-z0-9._/-]+\.(conf|pem)' /tmp/orbit-nginx-t.err 2>/dev/null || true)

  if [[ "$attempt" -eq 6 ]]; then
    echo "ERROR: nginx -t still failing" >&2
    exit 1
  fi
done

systemctl reload nginx
echo "Nginx reloaded."

sleep 1

# Verify public HTML is Next, not Roundcube
ROOT_BODY="$(curl -fsSL "https://${WEBMAIL_HOST}/" 2>/dev/null || curl -fsSL "https://${WEBMAIL_HOST}/webmail/login" 2>/dev/null || true)"
LOGIN_BODY="$(curl -fsSL "https://${WEBMAIL_HOST}/webmail/login" 2>/dev/null || true)"
COMBINED="${ROOT_BODY}${LOGIN_BODY}"

if printf '%s' "$COMBINED" | grep -Eiq 'skins/elastic|rcmlogin|roundcube'; then
  echo "FAIL: Public response still contains Roundcube markers" >&2
  echo "—— Enabled sites after cutover ——"
  ls -la /etc/nginx/sites-enabled/ || true
  echo "—— nginx -T server_name ${WEBMAIL_HOST} snippets ——"
  nginx -T 2>/dev/null | grep -nE "server_name|root |proxy_pass|roundcube" | head -100 || true
  exit 1
fi

if ! printf '%s' "$LOGIN_BODY" | grep -Eiq '_next/static|Sign In|Global Orbit Mail|/brand/'; then
  echo "WARN: Next.js markers not clearly detected — dump headers:"
  curl -sI "https://${WEBMAIL_HOST}/webmail/login" | head -30 || true
else
  echo "PASS: https://${WEBMAIL_HOST}/webmail/login is Next.js (not Roundcube)"
fi

echo
echo "DONE. Roundcube UI is no longer the public frontend."
echo "Proxy: https://${WEBMAIL_HOST} → http://${UPSTREAM}"
