#!/usr/bin/env bash
# GLOBAL ORBIT MAIL — VPS mail agent (production)
# Install: /opt/global-orbit/bin/mail-agent.sh && chmod 755
#
# Critical: this agent writes Dovecot credentials into PostgreSQL virtual_users
# using hashes generated by `doveadm pw` so the scheme ALWAYS matches live Dovecot.
set -euo pipefail

COMMAND="${1:-}"
PAYLOAD="${MAIL_AGENT_PAYLOAD:-{}}"

VMAIL_BASE="${VMAIL_BASE:-/var/mail/vhosts}"
VMAIL_UID="${VMAIL_UID:-5000}"
VMAIL_GID="${VMAIL_GID:-5000}"

json_ok() {
  local data="${1:-{}}"
  printf '{"ok":true,"data":%s}\n' "$data"
}

json_err() {
  local msg="$1"
  printf '{"ok":false,"error":%s}\n' "$(printf '%s' "$msg" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')"
  exit 1
}

field() {
  local key="$1"
  printf '%s' "$PAYLOAD" | python3 -c "
import json,sys
raw=sys.stdin.read() or '{}'
try:
  d=json.loads(raw)
except Exception:
  d={}
p=d.get('payload') if isinstance(d.get('payload'), dict) else {}
v=d.get('$key')
if v is None:
  v=p.get('$key')
print('' if v is None else v)
" 2>/dev/null || true
}

detect_scheme() {
  local scheme=""
  if command -v doveconf >/dev/null 2>&1; then
    scheme="$(doveconf -h auth_default_scheme 2>/dev/null || true)"
    if [[ -z "$scheme" ]]; then
      scheme="$(doveconf -h default_pass_scheme 2>/dev/null || true)"
    fi
  fi
  if [[ -z "$scheme" && -r /etc/dovecot/dovecot-sql.conf.ext ]]; then
    scheme="$(awk -F= '/^default_pass_scheme/{gsub(/[[:space:]]/,"",$2); print $2; exit}' /etc/dovecot/dovecot-sql.conf.ext 2>/dev/null || true)"
  fi
  # Prefer SHA512-CRYPT — universally available on Dovecot mail hosts.
  # BLF-CRYPT (bcrypt) is only used when Dovecot explicitly configures it.
  if [[ -z "$scheme" ]]; then
    scheme="SHA512-CRYPT"
  fi
  printf '%s' "$scheme"
}

sql_dsn() {
  # Prefer explicit DSN for the mail host DB (same DB Dovecot SQL passdb uses)
  if [[ -n "${MAIL_SQL_DSN:-}" ]]; then
    printf '%s' "$MAIL_SQL_DSN"
    return
  fi
  if [[ -n "${DATABASE_URL:-}" ]]; then
    printf '%s' "$DATABASE_URL"
    return
  fi
  if [[ -r /etc/dovecot/dovecot-sql.conf.ext ]]; then
    # connect = host=.. dbname=.. user=.. password=..
    local connect
    connect="$(awk -F= '/^connect/{sub(/^[^=]+=/,""); gsub(/^[[:space:]]+|[[:space:]]+$/,""); print; exit}' /etc/dovecot/dovecot-sql.conf.ext 2>/dev/null || true)"
    if [[ -n "$connect" ]]; then
      printf '%s' "$connect"
      return
    fi
  fi
  printf ''
}

psql_exec() {
  local sql="$1"
  local dsn
  dsn="$(sql_dsn)"
  if [[ -z "$dsn" ]]; then
    return 1
  fi
  if [[ "$dsn" == postgres*://* || "$dsn" == postgresql*://* ]]; then
    psql "$dsn" -v ON_ERROR_STOP=1 -c "$sql" >/dev/null
  else
    # libpq keyword style: host= dbname= user= password=
    # shellcheck disable=SC2086
    psql $dsn -v ON_ERROR_STOP=1 -c "$sql" >/dev/null
  fi
}

ensure_virtual_tables() {
  psql_exec "
    CREATE TABLE IF NOT EXISTS virtual_domains (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      active BOOLEAN NOT NULL DEFAULT true
    );
    CREATE TABLE IF NOT EXISTS virtual_users (
      id SERIAL PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      password TEXT NOT NULL,
      domain TEXT NOT NULL,
      quota_bytes BIGINT NOT NULL DEFAULT 0,
      active BOOLEAN NOT NULL DEFAULT true,
      home TEXT,
      uid INTEGER,
      gid INTEGER
    );
    ALTER TABLE virtual_users ADD COLUMN IF NOT EXISTS home TEXT;
    ALTER TABLE virtual_users ADD COLUMN IF NOT EXISTS uid INTEGER;
    ALTER TABLE virtual_users ADD COLUMN IF NOT EXISTS gid INTEGER;
  " || true
}

sql_escape() {
  printf '%s' "$1" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read())[1:-1])'
}

upsert_virtual_user() {
  local email="$1" hash="$2" quota_bytes="$3" home="$4"
  local domain
  domain="${email#*@}"
  ensure_virtual_tables
  local e d h hm
  e="$(sql_escape "$email")"
  d="$(sql_escape "$domain")"
  h="$(sql_escape "$hash")"
  hm="$(sql_escape "$home")"
  psql_exec "INSERT INTO virtual_domains (name, active) VALUES (E'$d', true) ON CONFLICT (name) DO UPDATE SET active = true;"
  psql_exec "
    INSERT INTO virtual_users (email, password, domain, quota_bytes, active, home, uid, gid)
    VALUES (E'$e', E'$h', E'$d', ${quota_bytes:-0}, true, E'$hm', ${VMAIL_UID}, ${VMAIL_GID})
    ON CONFLICT (email) DO UPDATE SET
      password = EXCLUDED.password,
      quota_bytes = EXCLUDED.quota_bytes,
      active = true,
      home = EXCLUDED.home,
      uid = EXCLUDED.uid,
      gid = EXCLUDED.gid;
  "
}

hash_password_for_dovecot() {
  local plain="$1"
  local provided_hash="$2"
  local scheme
  scheme="$(detect_scheme)"

  if [[ -n "$plain" ]] && command -v doveadm >/dev/null 2>&1; then
    # Generate hash with the LIVE Dovecot binary — this is the only trustworthy scheme source.
    doveadm pw -s "$scheme" -p "$plain" | tr -d '\r\n'
    return
  fi

  if [[ -n "$plain" ]] && command -v openssl >/dev/null 2>&1; then
    # openssl -6 => SHA512-CRYPT ($6$)
    local out
    out="$(openssl passwd -6 "$plain" | tr -d '\r\n')"
    printf '{SHA512-CRYPT}%s' "$out"
    return
  fi

  if [[ -n "$provided_hash" ]]; then
    printf '%s' "$provided_hash"
    return
  fi

  return 1
}

ensure_maildir() {
  local email="$1"
  local localpart domain home
  localpart="${email%@*}"
  domain="${email#*@}"
  home="${VMAIL_BASE}/${domain}/${localpart}"

  mkdir -p \
    "${home}/cur" "${home}/new" "${home}/tmp" \
    "${home}/.Drafts/cur" "${home}/.Drafts/new" "${home}/.Drafts/tmp" \
    "${home}/.Sent/cur" "${home}/.Sent/new" "${home}/.Sent/tmp" \
    "${home}/.Junk/cur" "${home}/.Junk/new" "${home}/.Junk/tmp" \
    "${home}/.Trash/cur" "${home}/.Trash/new" "${home}/.Trash/tmp"

  if id -u "vmail" >/dev/null 2>&1; then
    chown -R "vmail:vmail" "${VMAIL_BASE}/${domain}" 2>/dev/null || chown -R "${VMAIL_UID}:${VMAIL_GID}" "${VMAIL_BASE}/${domain}" 2>/dev/null || true
  else
    chown -R "${VMAIL_UID}:${VMAIL_GID}" "${VMAIL_BASE}/${domain}" 2>/dev/null || true
  fi
  chmod -R u+rwX,g+rwX,o-rwx "${home}" 2>/dev/null || true
  printf '%s' "$home"
}

case "$COMMAND" in
  domain.create)
    domain="$(field domain)"
    domain="$(printf '%s' "$domain" | tr '[:upper:]' '[:lower:]')"
    if [[ -n "$domain" ]]; then
      mkdir -p "${VMAIL_BASE}/${domain}"
      ensure_virtual_tables
      d="$(sql_escape "$domain")"
      psql_exec "INSERT INTO virtual_domains (name, active) VALUES (E'$d', true) ON CONFLICT (name) DO UPDATE SET active = true;" || true
      if id -u "vmail" >/dev/null 2>&1; then
        chown -R "vmail:vmail" "${VMAIL_BASE}/${domain}" 2>/dev/null || true
      fi
    fi
    json_ok "{\"domain\":\"$domain\",\"action\":\"domain.create\"}"
    ;;
  domain.delete)
    domain="$(field domain)"
    json_ok "{\"domain\":\"$domain\",\"action\":\"domain.delete\"}"
    ;;
  mailbox.create|mailbox.password)
    email="$(field email)"
    email="$(printf '%s' "$email" | tr '[:upper:]' '[:lower:]')"
    plain="$(field password)"
    provided_hash="$(field mailPasswordHash)"
    quota_bytes="$(field quotaBytes)"
    quota_bytes="${quota_bytes:-0}"

    if [[ -z "$email" || "$email" != *"@"* ]]; then
      json_err "mailbox.create requires email"
    fi

    hash="$(hash_password_for_dovecot "$plain" "$provided_hash" || true)"
    if [[ -z "$hash" ]]; then
      json_err "Unable to hash password (need doveadm or openssl, or mailPasswordHash)"
    fi

    home="$(ensure_maildir "$email")"
    if ! upsert_virtual_user "$email" "$hash" "$quota_bytes" "$home"; then
      json_err "Failed writing virtual_users (set MAIL_SQL_DSN or DATABASE_URL on the mail host)"
    fi

    scheme="$(detect_scheme)"
    # Escape hash for JSON
    hash_json="$(printf '%s' "$hash" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')"
    json_ok "{\"email\":\"$email\",\"action\":\"$COMMAND\",\"home\":\"$home\",\"scheme\":\"$scheme\",\"mailPasswordHash\":$hash_json,\"sqlSynced\":true}"
    ;;
  mailbox.delete|mailbox.suspend)
    email="$(field email)"
    email="$(printf '%s' "$email" | tr '[:upper:]' '[:lower:]')"
    e="$(sql_escape "$email")"
    ensure_virtual_tables
    psql_exec "UPDATE virtual_users SET active = false WHERE email = E'$e';" || true
    json_ok "{\"email\":\"$email\",\"action\":\"$COMMAND\"}"
    ;;
  mailbox.unsuspend)
    email="$(field email)"
    email="$(printf '%s' "$email" | tr '[:upper:]' '[:lower:]')"
    e="$(sql_escape "$email")"
    ensure_virtual_tables
    psql_exec "UPDATE virtual_users SET active = true WHERE email = E'$e';" || true
    json_ok "{\"email\":\"$email\",\"action\":\"$COMMAND\"}"
    ;;
  mailbox.quota)
    email="$(field email)"
    json_ok "{\"email\":\"$email\",\"action\":\"mailbox.quota\"}"
    ;;
  alias.sync|forwarder.sync|vacation.sync|dkim.sync)
    json_ok "{\"action\":\"$COMMAND\"}"
    ;;
  storage.usage)
    email="$(field email)"
    used=0
    if command -v doveadm >/dev/null 2>&1 && [[ -n "$email" ]]; then
      used="$(doveadm quota get -u "$email" 2>/dev/null | awk '/STORAGE/{print $3; exit}' || echo 0)"
    fi
    json_ok "{\"email\":\"$email\",\"usedBytes\":${used:-0}}"
    ;;
  health.check)
    scheme="$(detect_scheme)"
    json_ok "{\"scheme\":\"$scheme\",\"vmailBase\":\"$VMAIL_BASE\"}"
    ;;
  *)
    json_err "Unknown command: $COMMAND"
    ;;
esac
