import {
  LayoutDashboard,
  Globe2,
  Inbox,
  Users,
  Network,
  FileText,
  ScrollText,
  Shield,
  Activity,
  CreditCard,
  Code2,
  Server,
  Settings,
  LifeBuoy,
  BookOpen,
  UserCircle,
  Building2,
  ShoppingCart,
  TrendingUp,
  BadgePercent,
  Wallet,
  Receipt,
  Layers,
  BarChart3,
  type LucideIcon,
} from "lucide-react";

export interface AdminNavItem {
  title: string;
  href: string;
  icon: LucideIcon;
}

export const adminNav: AdminNavItem[] = [
  { title: "Dashboard", href: "/orbit", icon: LayoutDashboard },
  { title: "Customers", href: "/orbit/customers", icon: Building2 },
  { title: "Orders", href: "/orbit/orders", icon: ShoppingCart },
  { title: "Revenue", href: "/orbit/revenue", icon: TrendingUp },
  { title: "Subscriptions", href: "/orbit/subscriptions", icon: Layers },
  { title: "Domains", href: "/orbit/domains", icon: Globe2 },
  { title: "Mailboxes", href: "/orbit/mailboxes", icon: Inbox },
  { title: "Users", href: "/orbit/users", icon: Users },
  { title: "DNS Manager", href: "/orbit/dns", icon: Network },
  { title: "DNS Templates", href: "/orbit/templates", icon: FileText },
  { title: "Plans", href: "/orbit/plans", icon: Layers },
  { title: "Coupons", href: "/orbit/coupons", icon: BadgePercent },
  { title: "Payments", href: "/orbit/payments", icon: Wallet },
  { title: "Invoices", href: "/orbit/invoices", icon: Receipt },
  { title: "Analytics", href: "/orbit/analytics", icon: BarChart3 },
  { title: "Logs", href: "/orbit/logs", icon: ScrollText },
  { title: "Security", href: "/orbit/security", icon: Shield },
  { title: "Monitoring", href: "/orbit/monitoring", icon: Activity },
  { title: "Billing", href: "/orbit/billing", icon: CreditCard },
  { title: "API", href: "/orbit/api", icon: Code2 },
  { title: "System", href: "/orbit/system", icon: Server },
  { title: "Profile", href: "/orbit/profile", icon: UserCircle },
  { title: "Settings", href: "/orbit/settings", icon: Settings },
  { title: "Support", href: "/orbit/support", icon: LifeBuoy },
  { title: "Documentation", href: "/orbit/documentation", icon: BookOpen },
];
