<?php
/**
 * GLOBAL ORBIT MAIL — Roundcube deliverability defaults
 *
 * Include from config.inc.php:
 *   include __DIR__ . '/deliverability.inc.php';
 *
 * Message-ID, Date, MIME-Version, and Content-Type are generated by Roundcube
 * on every compose/send. This file aligns SMTP HELO with reverse DNS and
 * keeps charset/MIME safe for Gmail/Outlook/Yahoo.
 *
 * IMPORTANT: smtp_helo_host MUST match the server PTR (FCrDNS).
 * Live PTR for 200.97.170.235 is currently mail.theglobalorbit.com.
 * Do not set this to a hostname that does not reverse-confirm.
 */

// Prefer env override when set by provisioning; otherwise PTR-aligned default
$orbitHelo = getenv('ORBIT_SMTP_HELO') ?: 'mail.theglobalorbit.com';
$config['smtp_helo_host'] = $orbitHelo;

$config['message_charset'] = 'UTF-8';
$config['http_received_host'] = 'webmail.globalorbitmail.cloud';
$config['force_7bit'] = false;
$config['mdn_use_from'] = true;

// Envelope / identity: use mailbox address as SMTP MAIL FROM (Return-Path)
// Roundcube already uses the selected identity email as envelope sender when
// smtp_user is the mailbox. Keep identities editable for display name only.
$config['smtp_log'] = false;
$config['smtp_debug'] = false;
